import './style.css'

const MARKER = '6b06ba62-a7bf-471c-90ec-9acd37811162'
const SIZE = 20
const directions = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } }
const app = document.querySelector('#app')
let mode = 'solo'; let name = 'PLAYER 01'; let scores = loadScores(); let game; let frame; let previous = 0
const defaults = [{ name: 'NOVA', score: 1240, mode: '单人', date: '今日' }, { name: 'BYTE', score: 980, mode: 'AI 对战', date: '昨日' }, { name: 'KAI', score: 760, mode: '双人', date: '09/18' }]
function loadScores() { try { return JSON.parse(localStorage.getItem('arena-snake-leaderboard')) || defaults } catch { return defaults } }
function saveScore(score) { scores = [...scores, { name, score, mode: mode === 'solo' ? '单人' : mode === 'ai' ? 'AI 对战' : '双人', date: '刚刚' }].sort((a, b) => b.score - a.score).slice(0, 8); try { localStorage.setItem('arena-snake-leaderboard', JSON.stringify(scores)) } catch { /* memory fallback */ } }
function opposite(a, b) { return a.x + b.x === 0 && a.y + b.y === 0 }
function openFood(snakes) { const blocked = new Set(snakes.flatMap(s => s.body).map(p => `${p.x},${p.y}`)); const open = []; for (let y = 0; y < SIZE; y++) for (let x = 0; x < SIZE; x++) if (!blocked.has(`${x},${y}`)) open.push({ x, y }); return open[Math.floor(Math.random() * open.length)] || { x: 0, y: 0 } }
function snake(start, direction, color) { return { body: [start, { x: start.x - direction.x, y: start.y - direction.y }, { x: start.x - direction.x * 2, y: start.y - direction.y * 2 }], direction, next: direction, color, alive: true, score: 0 } }
function card(value, title, label, copy, icon, number) { return `<button class="mode-card ${mode === value ? 'selected' : ''}" data-mode="${value}"><span class="mode-icon">${icon}</span><span class="mode-copy"><b>${title}</b><small>${label}</small><em>${copy}</em></span><span class="mode-number">${number}</span></button>` }
function row(item, i) { return `<div class="score-row"><span class="rank ${i === 0 ? 'gold' : ''}">${String(i + 1).padStart(2, '0')}</span><span class="avatar">${item.name[0]}</span><span class="score-name"><b>${item.name}</b><small>${item.mode}</small></span><strong>${item.score.toLocaleString()}</strong><span class="score-date">${item.date}</span></div>` }
function lobby() { app.innerHTML = `<main class="shell lobby-shell" data-workflow="${MARKER}"><header class="topbar"><div class="brand"><span class="brand-mark">+</span><span>ARENA<span class="brand-dim"> // SNAKE CIRCUIT</span></span></div><div class="top-meta"><span class="live-dot"></span> LIVE SYSTEM <span class="divider"></span> SEASON 04</div></header><section class="hero"><div class="eyebrow">WELCOME TO THE GRID <span>///</span> 2026.09</div><h1>成为<span>最快的蛇</span></h1><p>在霓虹网格中生存、成长、制霸排行榜。每一次转向，都是一场决策。</p><div class="hero-actions"><button class="primary-btn" id="enter-btn">进入赛场 <span>→</span></button><button class="ghost-btn" id="how-btn">操作说明 <span>⌁</span></button></div><div class="hero-stats"><div><strong>20 × 20</strong><small>竞技网格</small></div><div><strong>03</strong><small>游戏模式</small></div><div><strong>∞</strong><small>无限可能</small></div></div></section><section class="lobby-grid"><div class="panel modes-panel"><div class="panel-heading"><span><i class="section-index">01</i> 选择赛制</span><span class="panel-note">SELECT MODE</span></div><div class="mode-list">${card('solo', '单人冲刺', 'SOLO SPRINT', '与时间赛跑，刷新你的个人纪录。', '⌁', '01')}${card('versus', '双人对决', 'DUO DUEL', '同屏竞技，最后存活者获胜。', '◉', '02')}${card('ai', 'AI 猎手', 'AI HUNTER', '挑战三档智能，测试你的极限。', '✦', '03')}</div><div class="player-input"><label>参赛代号</label><input id="name-input" maxlength="14" value="${name}" /></div></div><div class="panel leaderboard-panel"><div class="panel-heading"><span><i class="section-index">02</i> 荣誉榜</span><span class="panel-note">TOP RUNNERS</span></div><div class="leaderboard">${scores.map(row).join('')}</div><div class="leaderboard-footer"><span><span class="live-dot"></span> 记录实时同步</span><span>查看全部 →</span></div></div></section><footer class="footer"><span>ARENA SYSTEMS <b>·</b> BUILT FOR THE BOLD</span><span>键盘方向键 / WASD 控制 <b>·</b> SPACE 暂停</span></footer></main>`; document.querySelector('#enter-btn').onclick = start; document.querySelector('#how-btn').onclick = () => alert('方向键或 WASD 移动，SPACE 暂停，R 重新开始。双人模式使用方向键与 IJKL 分别控制。'); document.querySelector('#name-input').oninput = e => { name = e.target.value.toUpperCase() || 'PLAYER 01' }; document.querySelectorAll('[data-mode]').forEach(button => { button.onclick = () => { mode = button.dataset.mode; lobby() } }) }
function start() { cancelAnimationFrame(frame); const first = snake({ x: 6, y: 10 }, directions.right, '#d5ff55'); const snakes = [first]; if (mode !== 'solo') snakes.push(snake({ x: 14, y: 10 }, directions.left, mode === 'ai' ? '#f58cff' : '#55d8ff')); game = { snakes, food: openFood(snakes), paused: false, over: false, ticks: 0 }; board(); frame = requestAnimationFrame(loop) }
function board() { app.innerHTML = `<main class="shell game-shell" data-workflow="${MARKER}"><header class="topbar"><button class="back-btn" id="back-btn">← 返回大厅</button><div class="brand"><span class="brand-mark">+</span><span>ARENA<span class="brand-dim"> // ${mode === 'solo' ? 'SOLO SPRINT' : mode === 'ai' ? 'AI HUNTER' : 'DUO DUEL'}</span></span></div><div class="top-meta"><span class="live-dot"></span> MATCH IN PROGRESS</div></header><section class="game-layout"><aside class="game-sidebar"><div class="match-label">MATCH 04 / ${mode.toUpperCase()}</div><div class="big-score"><small>YOUR SCORE</small><strong id="score-value">0000</strong><span><i class="trend">↑</i> 当前连胜中</span></div><div class="side-rule"></div><div class="stat-pair"><span>长度</span><b id="length-value">03</b></div><div class="stat-pair"><span>速度</span><b id="speed-value">1.0x</b></div><div class="stat-pair"><span>最佳</span><b>${scores[0]?.score.toLocaleString() || '0000'}</b></div><div class="control-card"><span class="control-title">控制方式</span><div class="key-hint"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><small>移动蛇身</small></div><div class="key-hint"><kbd>SPACE</kbd><small>暂停 / 继续</small></div></div><button class="pause-btn" id="pause-btn">暂停游戏 <span>Ⅱ</span></button></aside><section class="board-wrap"><div class="board-top"><div><span class="eyebrow">LIVE ARENA</span><h2>最后一条蛇站立</h2></div><div class="round-info"><span>ROUND <b>04</b></span><span>TIME <b id="time-value">00:00</b></span></div></div><div class="canvas-frame"><canvas id="game-canvas" width="600" height="600"></canvas><div class="canvas-overlay" id="overlay"></div></div><div class="board-bottom"><span><i class="legend-dot food-dot"></i> 能量核心</span><span><i class="legend-dot player-dot"></i> ${name}</span>${mode !== 'solo' ? '<span><i class="legend-dot rival-dot"></i> 对手</span>' : ''}<span class="tip">吃到核心获得 10 分 · 撞墙即出局</span></div></section></section></main>`; document.querySelector('#back-btn').onclick = lobby; document.querySelector('#pause-btn').onclick = pause }
function pause() { game.paused = !game.paused; document.querySelector('#pause-btn').innerHTML = game.paused ? '继续游戏 <span>▶</span>' : '暂停游戏 <span>Ⅱ</span>'; document.querySelector('#overlay').innerHTML = game.paused ? '<div class="paused-label">PAUSED<span>按 SPACE 继续</span></div>' : '' }
function aiDirection(s) { const opts = Object.values(directions).filter(d => !opposite(s.direction, d)); return opts.sort((a, b) => Math.abs(s.body[0].x + a.x - game.food.x) + Math.abs(s.body[0].y + a.y - game.food.y) - Math.abs(s.body[0].x + b.x - game.food.x) - Math.abs(s.body[0].y + b.y - game.food.y))[0] }
function step() { if (game.paused || game.over) return; game.ticks++; game.snakes.forEach((s, index) => { if (!s.alive) return; if (mode === 'ai' && index === 1) s.next = aiDirection(s); const head = s.body[0]; const next = { x: head.x + s.next.x, y: head.y + s.next.y }; const hit = next.x < 0 || next.y < 0 || next.x >= SIZE || next.y >= SIZE || s.body.slice(0, -1).some(p => p.x === next.x && p.y === next.y) || game.snakes.some((other, rival) => rival !== index && other.body.some(p => p.x === next.x && p.y === next.y)); if (hit) { s.alive = false; return } s.direction = s.next; s.body.unshift(next); if (next.x === game.food.x && next.y === game.food.y) { s.score += 10; game.food = openFood(game.snakes) } else s.body.pop() }); if ((mode === 'solo' && !game.snakes[0].alive) || (mode !== 'solo' && game.snakes.filter(s => s.alive).length < 2)) finish() }
function draw() { const canvas = document.querySelector('#game-canvas'); if (!canvas) return; const ctx = canvas.getContext('2d'); const cell = canvas.width / SIZE; ctx.fillStyle = '#101721'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = 'rgba(125,153,176,.11)'; for (let i = 1; i < SIZE; i++) { ctx.beginPath(); ctx.moveTo(i * cell, 0); ctx.lineTo(i * cell, canvas.height); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, i * cell); ctx.lineTo(canvas.width, i * cell); ctx.stroke() } ctx.shadowBlur = 18; ctx.shadowColor = '#f58cff'; ctx.fillStyle = '#f58cff'; ctx.beginPath(); ctx.arc(game.food.x * cell + cell / 2, game.food.y * cell + cell / 2, cell * .27, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; game.snakes.forEach(s => s.body.forEach((p, i) => { ctx.fillStyle = s.alive ? s.color : '#495466'; ctx.globalAlpha = i ? Math.max(.35, 1 - i / 30) : 1; ctx.beginPath(); ctx.roundRect(p.x * cell + 3, p.y * cell + 3, cell - 6, cell - 6, i ? 4 : 7); ctx.fill() })); ctx.globalAlpha = 1; document.querySelector('#score-value').textContent = String(game.snakes[0].score).padStart(4, '0'); document.querySelector('#length-value').textContent = String(game.snakes[0].body.length).padStart(2, '0'); document.querySelector('#speed-value').textContent = `${(1 + Math.min(1.5, game.ticks / 150)).toFixed(1)}x`; document.querySelector('#time-value').textContent = new Date(game.ticks * 130).toISOString().substring(14, 19) }
function loop(time) { if (!previous) previous = time; if (time - previous > 130) { step(); previous = time } draw(); if (!game.over) frame = requestAnimationFrame(loop) }
function finish() { game.over = true; const score = game.snakes[0].score; if (score) saveScore(score); document.querySelector('#overlay').innerHTML = `<div class="game-over"><span class="eyebrow">MATCH COMPLETE</span><h3>${game.snakes[0].alive ? '你赢了' : '继续训练'}</h3><strong>${score.toLocaleString()}</strong><small>最终得分</small><button class="primary-btn" id="retry-btn">再来一局 <span>→</span></button></div>`; document.querySelector('#retry-btn').onclick = start }
document.addEventListener('keydown', e => { if (!game || game.over) return; if (e.key === ' ') { e.preventDefault(); pause(); return } if (e.key.toLowerCase() === 'r') { start(); return } const map = { ArrowUp: directions.up, ArrowDown: directions.down, ArrowLeft: directions.left, ArrowRight: directions.right, w: directions.up, s: directions.down, a: directions.left, d: directions.right }; const d = map[e.key] || map[e.key.toLowerCase()]; if (d && !opposite(game.snakes[0].direction, d)) game.snakes[0].next = d; if (mode === 'versus') { const rival = { i: directions.up, k: directions.down, j: directions.left, l: directions.right }[e.key.toLowerCase()]; if (rival && !opposite(game.snakes[1].direction, rival)) game.snakes[1].next = rival } })
lobby()
